server:
  port: 4040
spring:  application:    name: service-3
eureka:  client:    service-url:
      defaultZone: http://ec2-13-209-96-55.ap-northeast-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: ec2-52-78-167-183.ap-northeast-2.compute.amazonaws.com
management:  endpoints:    web:      exposure:        include: "*"

#---
#spring:
#  profiles: dev
#eureka:#  client:#    service-url:
#      defaultZone: http://ec2-13-209-96-55.ap-northeast-2.compute.amazonaws.com:8761/eureka/
#  instance:
#    hostname: ec2-52-78-167-183.ap-northeast-2.compute.amazonaws.com
# 