# yml(yaml, 야믈(야멀))
# 시스 설정에 사용하는 파일
spring:
  datasource:    driver-class-name: org.postgresql.Driver
    # jdbc - java database connector
    # :postresql - 데이터베이스 엔진
    # //url - 데이터베이스 주소
    # :5432 - 데이터베이스 접속 포트
    # /postgres - 접속할 데이터베이스
    url: jdbc:postgresql://database-1.cdhsln5tr3nf.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace
    username: postgres
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true